### ISSUE TITLE
Prefer arrow functions

### ISSUE THREAD

**Issue by ericchu94** [kevinchu93/first-blog-mern#5]
https://github.com/kevinchu93/first-blog-mern/blob/25e742aa4aabf753eaa86f3c7fcbf7215b975a11/app.js#L18

In general, you should prefer [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) over anonymous functions

**Comment by kevinchu93** [comment]
changed
